from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from knowledge import build_indexes, inspect_bundle
from repo_context import (
    DEFAULT_MANIFEST_PATH,
    check_context,
    find_context,
    impact_context,
    verify_knowledge,
)


GENERATED_INDEX_MARKERS = (
    "Generated by engineering-workflow OKF knowledge index builder.",
    "Generated by repo-knowledge-engineering",
)
MAX_ASSESSMENT_DETAILS = 20
MAX_MATCHED_TERMS = 12


class DocumentationError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        json.dump(payload, stream, indent=2)
        stream.write("\n")


def git_output(root: Path, arguments: list[str]) -> str:
    try:
        result = subprocess.run(
            ["git", *arguments],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError as error:
        raise DocumentationError("documentation_git_unavailable", str(error)) from error
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "Git command failed."
        raise DocumentationError("documentation_git_failed", detail)
    return result.stdout


def changed_paths(root: Path, base: str) -> tuple[str, list[str]]:
    resolved_base = git_output(
        root, ["rev-parse", "--verify", "--end-of-options", base]
    ).strip()
    tracked = git_output(
        root, ["diff", "--name-only", "--diff-filter=ACMRD", resolved_base, "--"]
    ).splitlines()
    untracked = git_output(root, ["ls-files", "--others", "--exclude-standard"]).splitlines()
    paths = sorted({Path(value).as_posix() for value in tracked + untracked if value.strip()})
    return resolved_base, paths


def material_path(root: Path, relative: str) -> bool:
    if relative.startswith((".engineering-workflow/", "local-docs/")):
        return False
    if relative in {"version-metadata.json", DEFAULT_MANIFEST_PATH} or "/__pycache__/" in f"/{relative}/":
        return False
    target = root / relative
    if target.name == "index.md" and target.is_file():
        try:
            content = target.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return True
        if any(marker in content for marker in GENERATED_INDEX_MARKERS):
            return False
    return True


def delta_fingerprint(root: Path, base_revision: str, paths: list[str]) -> str:
    records: list[dict[str, str]] = []
    for relative in paths:
        target = root / relative
        if target.is_file():
            digest = hashlib.sha256(target.read_bytes()).hexdigest()
        else:
            digest = "deleted"
        records.append({"path": relative, "sha256": digest})
    encoded = json.dumps(
        {"baseRevision": base_revision, "files": records},
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def generation_context(root: Path, changed: list[str]) -> dict[str, Any]:
    rules: set[Path] = set()
    root_resolved = root.resolve()
    root_rules = root_resolved / "AGENTS.md"
    if root_rules.is_file():
        rules.add(root_rules)
    for relative in changed:
        current = (root_resolved / relative).parent
        while current.is_relative_to(root_resolved):
            candidate = current / "AGENTS.md"
            if candidate.is_file():
                rules.add(candidate)
            if current == root_resolved:
                break
            current = current.parent
    ordered_rules = sorted(
        rules,
        key=lambda path: (len(path.relative_to(root_resolved).parts), path.as_posix()),
    )
    entry_points = [
        relative
        for relative in ("README.md", "docs/knowledge/index.md")
        if (root_resolved / relative).is_file()
    ]
    return {
        "rulePaths": [path.relative_to(root_resolved).as_posix() for path in ordered_rules],
        "ruleHashes": {
            path.relative_to(root_resolved).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in ordered_rules
        },
        "canonicalEntryPoints": entry_points,
        "constraints": [
            "follow-applicable-repository-rules",
            "author-minimum-durable-truth",
            "preserve-truth-surface-boundaries",
            "validate-findability-and-freshness",
        ],
    }


def compact_impacts(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    compacted: list[dict[str, Any]] = []
    for item in items[:MAX_ASSESSMENT_DETAILS]:
        detail = dict(item)
        matched_terms = detail.get("matchedTerms")
        if isinstance(matched_terms, list) and len(matched_terms) > MAX_MATCHED_TERMS:
            detail["matchedTermCount"] = len(matched_terms)
            detail["matchedTerms"] = matched_terms[:MAX_MATCHED_TERMS]
        compacted.append(detail)
    return compacted


def assess_documentation(
    root: Path,
    *,
    base: str,
    manifest: str = DEFAULT_MANIFEST_PATH,
) -> tuple[dict[str, Any], int]:
    base_revision, discovered = changed_paths(root, base)
    material = [path for path in discovered if material_path(root, path)]
    fingerprint = delta_fingerprint(root, base_revision, material)
    generation = generation_context(root, material)
    if not material:
        return (
            {
                "result": "documentation-assessed",
                "outcome": "no-op",
                "base": base,
                "baseRevision": base_revision,
                "assessmentId": fingerprint,
                "changedPaths": [],
                "changedPathCount": 0,
                "detailsTruncated": False,
                "affectedKnowledge": [],
                "requiredActions": [],
                "generationContext": generation,
                "impactCounts": {
                    "boundImpacts": 0,
                    "candidateImpacts": 0,
                    "unmappedChanges": 0,
                },
            },
            0,
        )
    impact = impact_context(root, material, manifest=manifest)
    affected = sorted(
        {
            item["knowledgePath"]
            for item in impact["boundImpacts"] + impact["candidateImpacts"]
        }
    )
    if impact["unmappedChanges"] or impact["candidateImpacts"]:
        outcome = "decision-required"
        actions = ["classify-unmapped-or-candidate-changes"]
    else:
        outcome = "update"
        actions = ["review-and-align-affected-knowledge"]
    impact_counts = {
        key: len(impact[key])
        for key in ("boundImpacts", "candidateImpacts", "unmappedChanges")
    }
    details_truncated = len(material) > MAX_ASSESSMENT_DETAILS or any(
        count > MAX_ASSESSMENT_DETAILS for count in impact_counts.values()
    )
    return (
        {
            "result": "documentation-assessed",
            "outcome": outcome,
            "base": base,
            "baseRevision": base_revision,
            "assessmentId": fingerprint,
            "changedPaths": material[:MAX_ASSESSMENT_DETAILS],
            "changedPathCount": len(material),
            "detailsTruncated": details_truncated,
            "affectedKnowledge": affected,
            "requiredActions": actions,
            "generationContext": generation,
            "impactCounts": impact_counts,
            "impact": {
                "boundImpacts": compact_impacts(impact["boundImpacts"]),
                "candidateImpacts": compact_impacts(impact["candidateImpacts"]),
                "unmappedChanges": compact_impacts(impact["unmappedChanges"]),
            },
        },
        3,
    )


def explain_change(root: Path, *, base: str, summary: str) -> dict[str, Any]:
    if not summary.strip():
        raise DocumentationError(
            "change_explanation_empty", "A causal change summary is required."
        )
    base_revision, discovered = changed_paths(root, base)
    material = [path for path in discovered if material_path(root, path)]
    fingerprint = delta_fingerprint(root, base_revision, material)
    receipt = {
        "schemaVersion": 1,
        "base": base,
        "baseRevision": base_revision,
        "deltaFingerprint": fingerprint,
        "changedPaths": material,
        "summary": summary.strip(),
        "recordedAt": utc_now(),
    }
    write_json(root / ".engineering-workflow" / "change-explanation.json", receipt)
    return {"result": "change-explained", **receipt}


def apply_documentation(
    root: Path,
    *,
    base: str,
    bundle: str,
    knowledge_paths: list[str],
    evidence: str,
    reader_queries: list[str],
    manifest: str = DEFAULT_MANIFEST_PATH,
) -> dict[str, Any]:
    selected = sorted(set(knowledge_paths))
    if not selected:
        raise DocumentationError(
            "documentation_knowledge_missing", "At least one canonical knowledge path is required."
        )
    if not evidence.strip():
        raise DocumentationError(
            "documentation_evidence_missing", "Documentation review evidence is required."
        )
    queries = [query.strip() for query in reader_queries if query.strip()]
    if not queries:
        raise DocumentationError(
            "documentation_reader_query_missing",
            "At least one likely reader query is required.",
        )
    assessment, _ = assess_documentation(root, base=base, manifest=manifest)
    missing = sorted(set(assessment["affectedKnowledge"]) - set(selected))
    if missing:
        raise DocumentationError(
            "documentation_coverage_incomplete",
            "Affected canonical knowledge was not supplied: " + ", ".join(missing),
        )
    bundle_report, bundle_exit = inspect_bundle(root, bundle)
    if bundle_exit != 0:
        raise DocumentationError(
            "documentation_bundle_invalid",
            "Canonical knowledge bundle validation failed before index generation.",
        )
    index_result = build_indexes(root, bundle)
    reader_checks: list[dict[str, Any]] = []
    for query in queries:
        retrieval = find_context(root, query, limit=5)
        ranked_paths = [item["path"] for item in retrieval["results"]]
        matched = next((path for path in ranked_paths if path in selected), None)
        if matched is None:
            raise DocumentationError(
                "documentation_reader_check_failed",
                f"Reader query did not retrieve affected canonical knowledge: {query}",
            )
        reader_checks.append(
            {
                "query": query,
                "status": "passed",
                "matchedKnowledge": matched,
                "rank": ranked_paths.index(matched) + 1,
            }
        )
    verification = [
        verify_knowledge(root, path, evidence.strip(), manifest=manifest)
        for path in selected
    ]
    context = check_context(root, manifest=manifest)
    if context["knowledgeFreshness"] != "fresh":
        raise DocumentationError(
            "documentation_freshness_failed",
            "Canonical knowledge is not fresh after verification.",
        )
    receipt = {
        "schemaVersion": 1,
        "base": assessment["base"],
        "baseRevision": assessment["baseRevision"],
        "deltaFingerprint": assessment["assessmentId"],
        "outcome": assessment["outcome"],
        "changedPaths": assessment["changedPaths"],
        "knowledgePaths": selected,
        "evidence": evidence.strip(),
        "readerChecks": reader_checks,
        "generationContext": assessment["generationContext"],
        "recordedAt": utc_now(),
    }
    write_json(root / ".engineering-workflow" / "documentation-receipt.json", receipt)
    return {
        "result": "documentation-applied",
        **receipt,
        "knowledgeFreshness": context["knowledgeFreshness"],
        "bundle": bundle_report,
        "indexes": index_result,
        "verification": verification,
    }


def load_receipt(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return payload if isinstance(payload, dict) else None


def documentation_closure_evidence(
    root: Path,
    *,
    base: str,
    manifest: str = DEFAULT_MANIFEST_PATH,
) -> dict[str, Any]:
    assessment, _ = assess_documentation(root, base=base, manifest=manifest)
    if assessment["outcome"] == "no-op":
        return {
            "ready": True,
            "assessment": assessment,
            "change": {"status": "no-op", "issues": []},
            "knowledge": {"status": "no-op", "issues": []},
        }
    fingerprint = assessment["assessmentId"]
    change_receipt = load_receipt(
        root / ".engineering-workflow" / "change-explanation.json"
    )
    documentation_receipt = load_receipt(
        root / ".engineering-workflow" / "documentation-receipt.json"
    )
    change_issues: list[str] = []
    if change_receipt is None:
        change_issues.append("change-explanation-missing")
    elif change_receipt.get("deltaFingerprint") != fingerprint:
        change_issues.append("change-explanation-stale")
    knowledge_issues: list[str] = []
    if documentation_receipt is None:
        knowledge_issues.append("documentation-receipt-missing")
    elif documentation_receipt.get("deltaFingerprint") != fingerprint:
        knowledge_issues.append("documentation-receipt-stale")
    else:
        covered = set(documentation_receipt.get("knowledgePaths", []))
        if not set(assessment["affectedKnowledge"]).issubset(covered):
            knowledge_issues.append("documentation-coverage-incomplete")
        context = check_context(root, manifest=manifest)
        if context["knowledgeFreshness"] != "fresh":
            knowledge_issues.append("canonical-knowledge-not-fresh")
    return {
        "ready": not change_issues and not knowledge_issues,
        "assessment": assessment,
        "change": {
            "status": "pending" if change_issues else "receipt-current",
            "issues": change_issues,
        },
        "knowledge": {
            "status": "pending" if knowledge_issues else "receipt-current",
            "issues": knowledge_issues,
        },
    }
