from __future__ import annotations

import re
import json
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse

from repo_context import (
    DEFAULT_MANIFEST_PATH,
    load_knowledge_manifest,
    repository_relative_path,
    validate_source_pattern,
)

try:
    import yaml
except ImportError as error:  # pragma: no cover - environment guard
    raise SystemExit(
        "PyYAML is required for OKF knowledge operations. Install it with: python -m pip install PyYAML"
    ) from error


RESERVED_NAMES = {"index.md", "log.md"}
GENERATED_INDEX_MARKER = "<!-- Generated by engineering-workflow OKF knowledge index builder. -->"
LEGACY_GENERATED_INDEX_MARKER = "<!-- Generated by repo-knowledge-engineering OKF index builder. -->"
LINK_PATTERN = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
EXCLUDED_GRAPH_DIRECTORIES = {
    "generated",
    "runbooks",
    "scratch",
    "temp",
    "temporary",
    "vendor",
}
EXCLUDED_GRAPH_TYPES = {"log"}
EXCLUDED_GRAPH_TYPE_MARKERS = {"runbook", "handoff", "session", "temporary", "scratch"}


class KnowledgeError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def repository_path(root: Path, value: str, *, require_directory: bool = False) -> tuple[Path, str]:
    candidate = Path(value)
    if candidate.is_absolute():
        raise KnowledgeError("knowledge_path_escape", "Knowledge paths must be repository-relative.")
    resolved_root = root.resolve()
    target = (resolved_root / candidate).resolve()
    if not target.is_relative_to(resolved_root):
        raise KnowledgeError("knowledge_path_escape", "Knowledge paths must remain inside the repository.")
    if not target.exists():
        raise KnowledgeError("knowledge_path_missing", f"Knowledge path does not exist: {value}")
    if require_directory and not target.is_dir():
        raise KnowledgeError("knowledge_bundle_invalid", f"Knowledge bundle is not a directory: {value}")
    return target, target.relative_to(resolved_root).as_posix()


def parse_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError("missing leading YAML frontmatter")
    try:
        closing = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration as error:
        raise ValueError("frontmatter is not closed with ---") from error
    metadata = yaml.safe_load("\n".join(lines[1:closing]))
    if not isinstance(metadata, dict):
        raise ValueError("frontmatter must contain a YAML mapping")
    return metadata, "\n".join(lines[closing + 1 :])


def clean_link(value: str) -> str | None:
    raw = value.strip().split(maxsplit=1)[0].strip("<>")
    parsed = urlparse(raw)
    if parsed.scheme or parsed.netloc or raw.startswith("#"):
        return None
    return unquote(parsed.path) or None


def valid_timestamp(value: Any) -> bool:
    if isinstance(value, datetime):
        return value.tzinfo is not None
    if not isinstance(value, str) or not value.strip():
        return False
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return parsed.tzinfo is not None


def inspect_bundle(root: Path, bundle: str) -> tuple[dict[str, Any], int]:
    bundle_path, bundle_relative = repository_path(root, bundle, require_directory=True)
    errors: list[dict[str, str]] = []
    warnings: list[dict[str, str]] = []
    concepts: dict[Path, dict[str, Any]] = {}
    for path in sorted(bundle_path.rglob("*.md")):
        if path.name in RESERVED_NAMES:
            continue
        relative = path.relative_to(root).as_posix()
        try:
            metadata, body = parse_frontmatter(path)
        except (OSError, UnicodeDecodeError, ValueError) as error:
            errors.append({"path": relative, "message": str(error)})
            continue
        concept_type = metadata.get("type")
        if not isinstance(concept_type, str) or not concept_type.strip():
            errors.append({"path": relative, "message": "type must be a non-empty string"})
            continue
        for field in ("title", "description"):
            value = metadata.get(field)
            if not isinstance(value, str) or not value.strip():
                warnings.append({"path": relative, "message": f"recommended field {field!r} is missing or empty"})
        if "timestamp" not in metadata or not valid_timestamp(metadata.get("timestamp")):
            warnings.append({"path": relative, "message": "timestamp should be an ISO 8601 datetime with timezone"})
        normalised_type = concept_type.strip().lower()
        graph_excluded = (
            normalised_type in EXCLUDED_GRAPH_TYPES
            or any(marker in normalised_type for marker in EXCLUDED_GRAPH_TYPE_MARKERS)
            or any(
                part.lower() in EXCLUDED_GRAPH_DIRECTORIES
                for part in path.relative_to(bundle_path).parts[:-1]
            )
        )
        concepts[path.resolve()] = {
            "path": relative,
            "type": concept_type.strip(),
            "title": metadata.get("title"),
            "description": metadata.get("description"),
            "body": body,
            "graphExcluded": graph_excluded,
        }

    governed = {path: concept for path, concept in concepts.items() if not concept["graphExcluded"]}
    adjacency: dict[Path, set[Path]] = {path: set() for path in governed}
    for source, concept in governed.items():
        for raw_link in LINK_PATTERN.findall(concept["body"]):
            target_value = clean_link(raw_link)
            if not target_value:
                continue
            target = (source.parent / target_value).resolve()
            if target.is_dir():
                target = target / "index.md"
            if target in governed and target != source:
                adjacency[source].add(target)
                adjacency[target].add(source)

    orphans = sorted(governed[path]["path"] for path, links in adjacency.items() if not links and len(governed) > 1)
    for path in orphans:
        errors.append({"path": path, "message": "durable knowledge graph contains an orphan concept"})
    remaining = set(adjacency)
    components = 0
    while remaining:
        components += 1
        pending = [next(iter(remaining))]
        visited: set[Path] = set()
        while pending:
            current = pending.pop()
            if current in visited:
                continue
            visited.add(current)
            pending.extend(adjacency[current] - visited)
        remaining -= visited
    if components > 1:
        errors.append({"path": bundle_relative, "message": f"durable knowledge graph has {components} disconnected components"})

    payload = {
        "result": "knowledge-checked",
        "bundle": bundle_relative,
        "conformant": not errors,
        "conceptCount": len(concepts),
        "governedConceptCount": len(governed),
        "componentCount": components,
        "orphans": orphans,
        "concepts": [
            {key: value for key, value in concept.items() if key not in {"body", "graphExcluded"}}
            for concept in concepts.values()
        ],
        "errors": errors,
        "warnings": warnings,
    }
    return payload, 0 if not errors else 3


def display_name(value: str) -> str:
    return value.replace("-", " ").replace("_", " ").strip().title()


def generated_index(directory: Path, bundle: Path) -> str:
    lines: list[str] = []
    if directory == bundle:
        lines.extend(["---", 'okf_version: "0.1"', "---", ""])
    lines.extend([GENERATED_INDEX_MARKER, ""])
    concepts = sorted(path for path in directory.glob("*.md") if path.name not in RESERVED_NAMES)
    subdirectories = sorted(
        path for path in directory.iterdir() if path.is_dir() and any(path.rglob("*.md"))
    )
    if concepts:
        lines.extend(["# Concepts", ""])
        for path in concepts:
            metadata, _ = parse_frontmatter(path)
            title = metadata.get("title") if isinstance(metadata.get("title"), str) else display_name(path.stem)
            description = (
                metadata.get("description")
                if isinstance(metadata.get("description"), str)
                else "No description provided."
            )
            lines.append(f"- [{title}]({path.name}) - {description}")
        lines.append("")
    if subdirectories:
        lines.extend(["# Directories", ""])
        for path in subdirectories:
            title = display_name(path.name)
            lines.append(f"- [{title}]({path.name}/) - Knowledge concepts in the {title} group.")
        lines.append("")
    if not concepts and not subdirectories:
        heading = "Knowledge Bundle" if directory == bundle else display_name(directory.name)
        lines.extend([f"# {heading}", "", "No concepts are recorded yet.", ""])
    return "\n".join(lines).rstrip() + "\n"


def write_utf8_lf(path: Path, content: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(content)


def build_indexes(root: Path, bundle: str, *, force: bool = False) -> dict[str, Any]:
    bundle_path, bundle_relative = repository_path(root, bundle, require_directory=True)
    directories = {bundle_path}
    for path in bundle_path.rglob("*.md"):
        directories.add(path.parent)
    manual_indexes = []
    for directory in directories:
        index = directory / "index.md"
        if index.exists():
            content = index.read_text(encoding="utf-8")
            if not any(
                marker in content
                for marker in (GENERATED_INDEX_MARKER, LEGACY_GENERATED_INDEX_MARKER)
            ):
                manual_indexes.append(index.relative_to(root).as_posix())
    if manual_indexes and not force:
        raise KnowledgeError(
            "knowledge_index_owned",
            "Refusing to replace indexes not generated by engineering-workflow: "
            + ", ".join(sorted(manual_indexes)),
        )
    written: list[str] = []
    for directory in sorted(directories, key=lambda item: (len(item.parts), str(item)), reverse=True):
        index = directory / "index.md"
        write_utf8_lf(index, generated_index(directory, bundle_path))
        written.append(index.relative_to(root).as_posix())
    return {
        "result": "knowledge-indexes-built",
        "bundle": bundle_relative,
        "written": sorted(written),
    }


def register_knowledge(
    root: Path,
    knowledge: str,
    sources: list[str],
    *,
    manifest: str = DEFAULT_MANIFEST_PATH,
) -> dict[str, Any]:
    if not sources:
        raise KnowledgeError("knowledge_sources_missing", "At least one explicit source pattern is required.")
    _, knowledge_path = repository_relative_path(
        root,
        knowledge,
        escape_code="knowledge_path_escape",
        missing_code="knowledge_path_missing",
    )
    try:
        metadata, _ = parse_frontmatter(root / knowledge_path)
    except (OSError, UnicodeDecodeError, ValueError) as error:
        raise KnowledgeError(
            "knowledge_concept_invalid",
            f"Canonical knowledge must be a typed OKF concept: {error}",
        ) from error
    if not isinstance(metadata.get("type"), str) or not metadata["type"].strip():
        raise KnowledgeError(
            "knowledge_concept_invalid",
            "Canonical knowledge requires a non-empty OKF type.",
        )
    normalised_sources = list(dict.fromkeys(validate_source_pattern(source) for source in sources))
    target, manifest_relative, payload = load_knowledge_manifest(root, manifest)
    existing = next(
        (entry for entry in payload["knowledge"] if entry["path"] == knowledge_path),
        None,
    )
    verification_invalidated = False
    if existing is None:
        payload["knowledge"].append({"path": knowledge_path, "sources": normalised_sources})
    else:
        if existing["sources"] != normalised_sources:
            verification_invalidated = isinstance(existing.get("verified"), dict)
            existing.pop("verified", None)
        existing["sources"] = normalised_sources
    payload["knowledge"].sort(key=lambda entry: entry["path"])
    target.parent.mkdir(parents=True, exist_ok=True)
    write_utf8_lf(target, json.dumps(payload, indent=2) + "\n")
    return {
        "result": "knowledge-registered",
        "manifest": manifest_relative,
        "knowledgePath": knowledge_path,
        "sources": normalised_sources,
        "verificationInvalidated": verification_invalidated,
    }
