#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass, field
from datetime import date, datetime
from pathlib import Path
from urllib.parse import unquote, urlparse

try:
    import yaml
except ImportError as error:  # pragma: no cover - environment-specific guard
    raise SystemExit("PyYAML is required to validate OKF frontmatter. Install it with: python -m pip install PyYAML") from error


TARGET_VERSION = "0.1"
GENERATED_INDEX_MARKER = "<!-- Generated by repo-knowledge-engineering OKF index builder. -->"
RESERVED_NAMES = {"index.md", "log.md"}
LINK_PATTERN = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
DATE_HEADING_PATTERN = re.compile(r"(?m)^##\s+(\d{4}-\d{2}-\d{2})\s*$")


@dataclass
class Finding:
    path: str
    message: str


@dataclass
class Report:
    bundle: str
    target_version: str = TARGET_VERSION
    declared_version: str | None = None
    concepts: int = 0
    indexes: int = 0
    logs: int = 0
    errors: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)

    @property
    def conformant(self) -> bool:
        return not self.errors

    def to_dict(self) -> dict[str, object]:
        result = asdict(self)
        result["conformant"] = self.conformant
        return result


def relative(path: Path, bundle: Path) -> str:
    return path.relative_to(bundle).as_posix()


def parse_frontmatter(path: Path, *, required: bool) -> tuple[dict[str, object] | None, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        if required:
            raise ValueError("missing leading YAML frontmatter")
        return None, text
    end = next((index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"), None)
    if end is None:
        raise ValueError("frontmatter is not closed with ---")
    raw = "\n".join(lines[1:end])
    try:
        metadata = yaml.safe_load(raw) or {}
    except yaml.YAMLError as error:
        raise ValueError(f"frontmatter is not parseable YAML: {error}") from error
    if not isinstance(metadata, dict):
        raise ValueError("frontmatter must contain a YAML mapping")
    body = "\n".join(lines[end + 1:])
    return metadata, body


def validate_timestamp(value: object) -> bool:
    if isinstance(value, datetime):
        return True
    if not isinstance(value, str):
        return False
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return "T" in value


def validate_concept(path: Path, bundle: Path, report: Report) -> None:
    rel = relative(path, bundle)
    try:
        metadata, body = parse_frontmatter(path, required=True)
    except (OSError, UnicodeDecodeError, ValueError) as error:
        report.errors.append(Finding(rel, str(error)))
        return
    assert metadata is not None
    concept_type = metadata.get("type")
    if not isinstance(concept_type, str) or not concept_type.strip():
        report.errors.append(Finding(rel, "type must be a non-empty string"))
    for recommended in ("title", "description"):
        value = metadata.get(recommended)
        if not isinstance(value, str) or not value.strip():
            report.warnings.append(Finding(rel, f"recommended field {recommended!r} is missing or empty"))
    if "tags" in metadata and (
        not isinstance(metadata["tags"], list)
        or not all(isinstance(tag, str) and tag.strip() for tag in metadata["tags"])
    ):
        report.errors.append(Finding(rel, "tags must be a YAML list of non-empty strings"))
    if "timestamp" in metadata and not validate_timestamp(metadata["timestamp"]):
        report.errors.append(Finding(rel, "timestamp must be an ISO 8601 datetime"))
    if "resource" in metadata:
        resource = metadata["resource"]
        if not isinstance(resource, str) or not urlparse(resource).scheme:
            report.errors.append(Finding(rel, "resource must be an absolute URI when present"))
    validate_links(path, body, bundle, report)


def index_body_is_structured(body: str) -> tuple[bool, bool]:
    has_heading = bool(re.search(r"(?m)^#\s+\S", body))
    has_entry = bool(re.search(r"(?m)^\s*[-*]\s+\[[^\]]+\]\([^)]+\)", body))
    return has_heading, has_entry


def validate_index(path: Path, bundle: Path, report: Report, *, require_version: bool) -> None:
    rel = relative(path, bundle)
    is_root = path.parent == bundle
    try:
        metadata, body = parse_frontmatter(path, required=False)
    except (OSError, UnicodeDecodeError, ValueError) as error:
        report.errors.append(Finding(rel, str(error)))
        return
    if metadata is not None and not is_root:
        report.errors.append(Finding(rel, "frontmatter is only allowed on the bundle-root index.md"))
    if is_root:
        declared = metadata.get("okf_version") if metadata else None
        report.declared_version = str(declared) if declared is not None else None
        if require_version and report.declared_version != report.target_version:
            report.errors.append(Finding(rel, f"root index must declare okf_version {report.target_version!r}"))
        elif report.declared_version and report.declared_version != report.target_version:
            report.warnings.append(Finding(rel, f"bundle declares OKF {report.declared_version!r}; validator targets {report.target_version!r}"))
        elif not report.declared_version:
            report.warnings.append(Finding(rel, "root index does not declare okf_version"))
    has_heading, has_entry = index_body_is_structured(body)
    if not has_heading:
        report.errors.append(Finding(rel, "index must contain at least one level-one section heading"))
    if not has_entry:
        report.warnings.append(Finding(rel, "index has no linked entries"))
    validate_links(path, body, bundle, report)


def validate_log(path: Path, bundle: Path, report: Report) -> None:
    rel = relative(path, bundle)
    try:
        metadata, body = parse_frontmatter(path, required=False)
    except (OSError, UnicodeDecodeError, ValueError) as error:
        report.errors.append(Finding(rel, str(error)))
        return
    if metadata is not None:
        report.errors.append(Finding(rel, "log.md must not contain frontmatter"))
    if not re.search(r"(?m)^#\s+\S", body):
        report.errors.append(Finding(rel, "log must contain a level-one heading"))
    headings = DATE_HEADING_PATTERN.findall(body)
    if not headings:
        report.errors.append(Finding(rel, "log must contain ISO date headings in YYYY-MM-DD form"))
        return
    parsed_dates: list[date] = []
    for value in headings:
        try:
            parsed_dates.append(date.fromisoformat(value))
        except ValueError:
            report.errors.append(Finding(rel, f"invalid log date heading: {value}"))
    if parsed_dates != sorted(parsed_dates, reverse=True):
        report.errors.append(Finding(rel, "log date headings must be newest first"))
    sections = re.split(r"(?m)^##\s+\d{4}-\d{2}-\d{2}\s*$", body)[1:]
    if any(not re.search(r"(?m)^\s*[-*]\s+\S", section) for section in sections):
        report.errors.append(Finding(rel, "each dated log section must contain at least one list entry"))
    validate_links(path, body, bundle, report)


def clean_link_target(raw: str) -> str:
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        target = target[1:target.index(">")]
    else:
        target = re.split(r"\s+(?=[\"'])", target, maxsplit=1)[0]
    return unquote(target.split("#", 1)[0].split("?", 1)[0])


def validate_links(source: Path, body: str, bundle: Path, report: Report) -> None:
    for raw in LINK_PATTERN.findall(body):
        target = clean_link_target(raw)
        if not target or target.startswith("#"):
            continue
        parsed = urlparse(target)
        if parsed.scheme or target.startswith("//"):
            continue
        resolved = (bundle / target.lstrip("/")) if target.startswith("/") else (source.parent / target)
        resolved = resolved.resolve()
        try:
            resolved.relative_to(bundle)
        except ValueError:
            report.warnings.append(Finding(relative(source, bundle), f"internal link leaves the bundle: {raw}"))
            continue
        if resolved.is_dir():
            resolved = resolved / "index.md"
        if Path(target).suffix and Path(target).suffix.lower() != ".md":
            continue
        if not resolved.exists():
            report.warnings.append(Finding(relative(source, bundle), f"broken internal link tolerated by OKF: {raw}"))


def validate_bundle(bundle: Path, *, require_version: bool = False) -> Report:
    bundle = bundle.resolve()
    report = Report(bundle=str(bundle))
    if not bundle.is_dir():
        report.errors.append(Finding(".", "bundle path is not a directory"))
        return report
    markdown_files = sorted(bundle.rglob("*.md"))
    for path in markdown_files:
        if path.name == "index.md":
            report.indexes += 1
            validate_index(path, bundle, report, require_version=require_version)
        elif path.name == "log.md":
            report.logs += 1
            validate_log(path, bundle, report)
        else:
            report.concepts += 1
            validate_concept(path, bundle, report)
    if require_version and not (bundle / "index.md").exists():
        report.errors.append(Finding("index.md", "versioned profile requires a bundle-root index.md"))
    if report.concepts == 0:
        report.warnings.append(Finding(".", "bundle contains no concept documents"))
    return report


def title_from_name(name: str) -> str:
    return name.replace("-", " ").replace("_", " ").strip().title()


def concept_summary(path: Path) -> tuple[str, str]:
    metadata, _ = parse_frontmatter(path, required=True)
    assert metadata is not None
    title = metadata.get("title") if isinstance(metadata.get("title"), str) else title_from_name(path.stem)
    description = metadata.get("description") if isinstance(metadata.get("description"), str) else "No description provided."
    return title, description


def generated_index(directory: Path, bundle: Path) -> str:
    is_root = directory == bundle
    lines: list[str] = []
    if is_root:
        lines.extend(["---", f'okf_version: "{TARGET_VERSION}"', "---", ""])
    lines.extend([GENERATED_INDEX_MARKER, ""])
    heading = "Knowledge Bundle" if is_root else title_from_name(directory.name)
    concepts = sorted(path for path in directory.glob("*.md") if path.name not in RESERVED_NAMES)
    subdirectories = sorted(
        path for path in directory.iterdir()
        if path.is_dir() and any(path.rglob("*.md"))
    )
    if concepts:
        lines.extend(["# Concepts", ""])
        for path in concepts:
            title, description = concept_summary(path)
            lines.append(f"- [{title}]({path.name}) - {description}")
        lines.append("")
    if subdirectories:
        lines.extend(["# Directories", ""])
        for path in subdirectories:
            title = title_from_name(path.name)
            lines.append(f"- [{title}]({path.name}/) - Knowledge concepts in the {title} group.")
        lines.append("")
    if not concepts and not subdirectories:
        lines.extend([f"# {heading}", "", "No concepts are recorded yet.", ""])
    return "\n".join(lines).rstrip() + "\n"


def build_indexes(bundle: Path, *, force: bool = False) -> list[Path]:
    bundle = bundle.resolve()
    if not bundle.is_dir():
        raise SystemExit(f"Bundle path is not a directory: {bundle}")
    directories = {bundle}
    for path in bundle.rglob("*.md"):
        directories.add(path.parent)
    manual_indexes = []
    for directory in directories:
        index = directory / "index.md"
        if index.exists() and GENERATED_INDEX_MARKER not in index.read_text(encoding="utf-8"):
            manual_indexes.append(index)
    if manual_indexes and not force:
        paths = "\n".join(f"- {path}" for path in sorted(manual_indexes))
        raise SystemExit(
            "Refusing to overwrite indexes not created by this generator:\n"
            f"{paths}\nUse --force only after confirming those indexes are safe to replace."
        )
    written: list[Path] = []
    for directory in sorted(directories, key=lambda item: (len(item.parts), str(item)), reverse=True):
        index = directory / "index.md"
        index.write_text(generated_index(directory, bundle), encoding="utf-8")
        written.append(index)
    return sorted(written)


def print_report(report: Report, *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(report.to_dict(), indent=2))
        return
    state = "conformant" if report.conformant else "not conformant"
    print(f"OKF {report.target_version}: {state}")
    print(f"Concepts: {report.concepts}; indexes: {report.indexes}; logs: {report.logs}")
    for finding in report.errors:
        print(f"ERROR {finding.path}: {finding.message}")
    for finding in report.warnings:
        print(f"WARN  {finding.path}: {finding.message}")


def validate_command(args: argparse.Namespace) -> int:
    report = validate_bundle(Path(args.bundle), require_version=args.require_version)
    print_report(report, as_json=args.json)
    return 1 if report.errors or (args.strict_warnings and report.warnings) else 0


def build_index_command(args: argparse.Namespace) -> int:
    paths = build_indexes(Path(args.bundle), force=args.force)
    for path in paths:
        print(path)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build indexes and validate Open Knowledge Format 0.1 bundles.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    validate = subparsers.add_parser("validate")
    validate.add_argument("--bundle", required=True)
    validate.add_argument("--require-version", action="store_true")
    validate.add_argument("--strict-warnings", action="store_true")
    validate.add_argument("--json", action="store_true")
    validate.set_defaults(func=validate_command)
    indexes = subparsers.add_parser("build-indexes")
    indexes.add_argument("--bundle", required=True)
    indexes.add_argument("--force", action="store_true")
    indexes.set_defaults(func=build_index_command)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
