#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = SKILL_DIR / "assets"
STATUSES = (
    "proposed",
    "ready",
    "in-progress",
    "blocked",
    "validation",
    "done",
    "superseded",
    "deferred",
)
TERMINAL_WORKSTREAM_STATUSES = {"done", "superseded", "deferred"}
TRANSITIONS = {
    "proposed": {"ready", "deferred", "superseded"},
    "ready": {"in-progress", "deferred", "superseded"},
    "in-progress": {"blocked", "validation", "deferred", "superseded"},
    "blocked": {"in-progress", "deferred", "superseded"},
    "validation": {"in-progress", "blocked", "done"},
    "done": {"superseded"},
    "deferred": {"ready", "superseded"},
    "superseded": set(),
}
SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def fail(message: str) -> None:
    raise SystemExit(message)


def valid_slug(value: str) -> str:
    if not SLUG_PATTERN.fullmatch(value):
        fail(f"Invalid slug {value!r}; use lowercase kebab-case.")
    return value


def read_template(name: str) -> str:
    return (ASSETS_DIR / name).read_text(encoding="utf-8")


def render(name: str, values: dict[str, str]) -> str:
    text = read_template(name)
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)
    return text.rstrip() + "\n"


def write_new(path: Path, content: str) -> None:
    if path.exists():
        fail(f"Refusing to overwrite existing record: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if len(lines) < 3 or lines[0] != "---":
        fail(f"Missing frontmatter in {path}")
    try:
        end = lines.index("---", 1)
    except ValueError:
        fail(f"Unclosed frontmatter in {path}")
    result: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        if ":" not in line:
            fail(f"Invalid frontmatter line in {path}: {line}")
        key, raw = line.split(":", 1)
        raw = raw.strip()
        if raw.startswith('"'):
            try:
                value = json.loads(raw)
            except json.JSONDecodeError as error:
                fail(f"Invalid quoted value in {path}: {error}")
        else:
            value = raw
        result[key.strip()] = str(value)
    return result


def replace_field(path: Path, field: str, value: str) -> None:
    text = path.read_text(encoding="utf-8")
    replacement = f"{field}: {scalar(value)}"
    updated, count = re.subn(rf"(?m)^{re.escape(field)}:\s*.*$", replacement, text, count=1)
    if count != 1:
        fail(f"Field {field!r} missing or duplicated in {path}")
    path.write_text(updated, encoding="utf-8")


def task_path(root: Path, slug: str) -> Path:
    return root / "tasks" / slug / "task.md"


def workstream_path(root: Path, task: str, slug: str) -> Path:
    return root / "tasks" / task / "workstreams" / f"{slug}.md"


def task_records(root: Path) -> list[tuple[Path, dict[str, str]]]:
    return [
        (path, parse_frontmatter(path))
        for path in sorted((root / "tasks").glob("*/task.md"))
    ]


def generated_index(root: Path) -> str:
    rows = []
    for path, record in task_records(root):
        rows.append(
            f"| [{record['title']}](./{record['task']}/task.md) | {record['status']} | "
            f"{record.get('owner') or 'unassigned'} | {record['updated']} |"
        )
    body = "\n".join(rows) if rows else "| _No tasks_ |  |  |  |"
    return (
        "<!-- Generated by repo-task-lifecycle. Do not edit by hand. -->\n"
        "# Task index\n\n"
        "| Task | Status | Owner | Updated |\n"
        "| --- | --- | --- | --- |\n"
        f"{body}\n"
    )


def build_index(root: Path) -> None:
    index = root / "tasks" / "index.md"
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(generated_index(root), encoding="utf-8")


def init_task(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    slug = valid_slug(args.slug)
    today = date.today().isoformat()
    content = render("task.md.template", {
        "task": scalar(slug),
        "title": scalar(args.title),
        "title_text": args.title,
        "status": scalar("proposed"),
        "owner": scalar(args.owner or ""),
        "created": scalar(today),
        "updated": scalar(today),
    })
    write_new(task_path(root, slug), content)
    (root / "tasks" / slug / "workstreams").mkdir(parents=True, exist_ok=True)
    build_index(root)
    return 0


def add_workstream(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    task = valid_slug(args.task)
    slug = valid_slug(args.slug)
    if not task_path(root, task).exists():
        fail(f"Task does not exist: {task}")
    content = render("workstream.md.template", {
        "task": scalar(task),
        "workstream": scalar(slug),
        "title": scalar(args.title),
        "title_text": args.title,
        "status": scalar("ready"),
        "owner": scalar(args.owner),
        "branch": scalar(args.branch),
        "updated": scalar(date.today().isoformat()),
    })
    write_new(workstream_path(root, task, slug), content)
    return 0


def transition(path: Path, target: str, force: bool) -> None:
    record = parse_frontmatter(path)
    current = record.get("status")
    if current not in STATUSES:
        fail(f"Unknown current status {current!r} in {path}")
    if target != current and target not in TRANSITIONS[current] and not force:
        fail(f"Invalid transition {current!r} -> {target!r}; use --force only for a documented correction.")
    replace_field(path, "status", target)
    replace_field(path, "updated", date.today().isoformat())


def set_status(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    task = valid_slug(args.task)
    path = workstream_path(root, task, valid_slug(args.workstream)) if args.workstream else task_path(root, task)
    if not path.exists():
        fail(f"Record does not exist: {path}")
    if not args.workstream and args.status == "done":
        incomplete = []
        for candidate in sorted(path.parent.joinpath("workstreams").glob("*.md")):
            record = parse_frontmatter(candidate)
            if record.get("status") not in TERMINAL_WORKSTREAM_STATUSES:
                incomplete.append(record.get("workstream", candidate.stem))
        if incomplete:
            fail("Task cannot be done while workstreams remain active: " + ", ".join(incomplete))
    transition(path, args.status, args.force)
    build_index(root)
    return 0


def validate(root: Path) -> list[str]:
    errors: list[str] = []
    branches: dict[str, Path] = {}
    for path, record in task_records(root):
        required = {"task", "title", "status", "owner", "created", "updated"}
        missing = required - record.keys()
        if missing:
            errors.append(f"{path}: missing {', '.join(sorted(missing))}")
            continue
        if record["task"] != path.parent.name or not SLUG_PATTERN.fullmatch(record["task"]):
            errors.append(f"{path}: task slug does not match its directory")
        if record["status"] not in STATUSES:
            errors.append(f"{path}: unknown status {record['status']!r}")
        workstreams = sorted(path.parent.joinpath("workstreams").glob("*.md"))
        for workstream_path_value in workstreams:
            workstream = parse_frontmatter(workstream_path_value)
            if workstream.get("task") != record["task"]:
                errors.append(f"{workstream_path_value}: parent task mismatch")
            if workstream.get("workstream") != workstream_path_value.stem:
                errors.append(f"{workstream_path_value}: workstream slug does not match filename")
            if workstream.get("status") not in STATUSES:
                errors.append(f"{workstream_path_value}: unknown status {workstream.get('status')!r}")
            branch = workstream.get("branch", "")
            if branch and workstream.get("status") not in TERMINAL_WORKSTREAM_STATUSES:
                if branch in branches:
                    errors.append(f"{workstream_path_value}: active branch also used by {branches[branch]}")
                branches[branch] = workstream_path_value
        if record["status"] == "done":
            active = [
                candidate.name
                for candidate in workstreams
                if parse_frontmatter(candidate).get("status") not in TERMINAL_WORKSTREAM_STATUSES
            ]
            if active:
                errors.append(f"{path}: done task has active workstreams: {', '.join(active)}")
    index = root / "tasks" / "index.md"
    if not index.exists():
        errors.append(f"{index}: generated index is missing")
    elif index.read_text(encoding="utf-8") != generated_index(root):
        errors.append(f"{index}: generated index is stale")
    return errors


def validate_command(args: argparse.Namespace) -> int:
    errors = validate(Path(args.root).resolve())
    if errors:
        fail("\n".join(errors))
    print("Task lifecycle surface is valid.")
    return 0


def build_index_command(args: argparse.Namespace) -> int:
    build_index(Path(args.root).resolve())
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Maintain repository-local task lifecycle records.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init")
    init_parser.add_argument("--root", required=True)
    init_parser.add_argument("--slug", required=True)
    init_parser.add_argument("--title", required=True)
    init_parser.add_argument("--owner")
    init_parser.set_defaults(func=init_task)

    workstream = subparsers.add_parser("add-workstream")
    workstream.add_argument("--root", required=True)
    workstream.add_argument("--task", required=True)
    workstream.add_argument("--slug", required=True)
    workstream.add_argument("--title", required=True)
    workstream.add_argument("--owner", required=True)
    workstream.add_argument("--branch", required=True)
    workstream.set_defaults(func=add_workstream)

    status = subparsers.add_parser("set-status")
    status.add_argument("--root", required=True)
    status.add_argument("--task", required=True)
    status.add_argument("--workstream")
    status.add_argument("--status", choices=STATUSES, required=True)
    status.add_argument("--force", action="store_true")
    status.set_defaults(func=set_status)

    index = subparsers.add_parser("build-index")
    index.add_argument("--root", required=True)
    index.set_defaults(func=build_index_command)

    validation = subparsers.add_parser("validate")
    validation.add_argument("--root", required=True)
    validation.set_defaults(func=validate_command)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
